// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:3bb7bc72-22b2-403b-9d75-5d6a6ca81d5c",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_BNr5uktJI",
    "aws_user_pools_web_client_id": "7uneid32rbi6638vurikm655ia"
};


export default awsmobile;
